version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: dockerfiles/django
    image: django:latest
    stdin_open: true
    tty: true
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: